apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # PostgreSQL переменные 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@db-service:5432/postgres
  
  # Redis переменные
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  REDIS_URL: redis://redis-service:6379/0
  
  # FastAPI
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  DEBUG: "true"
  
  # Grafana
  GRAFANA_ADMIN_PASSWORD: "2501"